# dbt_project.yml
name: 'financial_model'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  financial_model:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table

# dbt_project.yml end
